import { EditorElement, TextStyle, ImageElement, TextElement, ShapeElement } from '@/types';

export interface Template {
  id: string;
  name: string;
  category: string;
  thumbnail: string;
  canvas: {
    width: number;
    height: number;
    backgroundColor: string;
  };
  elements: EditorElement[];
}

const defaultTextStyle: TextStyle = {
  fontFamily: 'Arial',
  fontSize: 48,
  fontWeight: 'bold',
  color: '#ffffff',
  textAlign: 'center',
  lineHeight: 1.2,
  letterSpacing: 0,
};

export const TEMPLATES: Template[] = [
  {
    id: 'template-1',
    name: 'Bold Impact',
    category: 'Gaming',
    thumbnail: '/templates/bold-impact.jpg',
    canvas: { width: 1280, height: 720, backgroundColor: '#dc2626' },
    elements: [
      {
        id: 'bg-shape',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 1280, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        locked: false,
        visible: true,
        fill: '#dc2626',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'title',
        type: 'text',
        text: 'EPIC WIN',
        position: { x: 100, y: 250 },
        size: { width: 600, height: 100 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 72,
          color: '#ffffff',
          textShadow: '4px 4px 0px #000000',
          textAlign: 'left',
        },
      } as TextElement,
      {
        id: 'subtitle',
        type: 'text',
        text: 'Click to watch the full gameplay!',
        position: { x: 100, y: 370 },
        size: { width: 500, height: 50 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 24,
          color: '#fecaca',
          textAlign: 'left',
        },
      } as TextElement,
    ],
  },
  {
    id: 'template-2',
    name: 'Tech Review',
    category: 'Tech',
    thumbnail: '/templates/tech-review.jpg',
    canvas: { width: 1280, height: 720, backgroundColor: '#0f172a' },
    elements: [
      {
        id: 'bg',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 1280, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        locked: false,
        visible: true,
        fill: '#0f172a',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'accent',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 20, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        visible: true,
        fill: '#3b82f6',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'title',
        type: 'text',
        text: 'IPHONE 15 PRO\nREVIEW',
        position: { x: 60, y: 200 },
        size: { width: 700, height: 200 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 64,
          color: '#ffffff',
          textAlign: 'left',
          lineHeight: 1.1,
        },
      } as TextElement,
      {
        id: 'subtitle',
        type: 'text',
        text: 'Is it worth it?',
        position: { x: 60, y: 430 },
        size: { width: 400, height: 50 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 28,
          color: '#93c5fd',
          textAlign: 'left',
        },
      } as TextElement,
    ],
  },
  {
    id: 'template-3',
    name: 'Vlog Style',
    category: 'Vlog',
    thumbnail: '/templates/vlog-style.jpg',
    canvas: { width: 1280, height: 720, backgroundColor: '#fef3c7' },
    elements: [
      {
        id: 'bg',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 1280, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        locked: false,
        visible: true,
        fill: '#fef3c7',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'circle',
        type: 'shape',
        shapeType: 'circle',
        position: { x: 900, y: 100 },
        size: { width: 500, height: 500 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        visible: true,
        fill: '#fbbf24',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'title',
        type: 'text',
        text: 'DAY IN MY LIFE',
        position: { x: 80, y: 280 },
        size: { width: 600, height: 120 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 56,
          color: '#1f2937',
          textAlign: 'left',
        },
      } as TextElement,
      {
        id: 'subtitle',
        type: 'text',
        text: 'Los Angeles Edition',
        position: { x: 80, y: 410 },
        size: { width: 400, height: 50 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 24,
          color: '#92400e',
          textAlign: 'left',
        },
      } as TextElement,
    ],
  },
  {
    id: 'template-4',
    name: 'Tutorial',
    category: 'Education',
    thumbnail: '/templates/tutorial.jpg',
    canvas: { width: 1280, height: 720, backgroundColor: '#ecfdf5' },
    elements: [
      {
        id: 'bg',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 1280, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        locked: false,
        visible: true,
        fill: '#ecfdf5',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'badge',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 80, y: 180 },
        size: { width: 200, height: 40 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        visible: true,
        fill: '#10b981',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'badge-text',
        type: 'text',
        text: 'TUTORIAL',
        position: { x: 80, y: 180 },
        size: { width: 200, height: 40 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 18,
          color: '#ffffff',
          textAlign: 'center',
        },
      } as TextElement,
      {
        id: 'title',
        type: 'text',
        text: 'How to Master\nReact Hooks',
        position: { x: 80, y: 250 },
        size: { width: 700, height: 200 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 56,
          color: '#064e3b',
          textAlign: 'left',
          lineHeight: 1.15,
        },
      } as TextElement,
      {
        id: 'time',
        type: 'text',
        text: '15 min read',
        position: { x: 80, y: 480 },
        size: { width: 300, height: 50 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 20,
          color: '#059669',
          textAlign: 'left',
        },
      } as TextElement,
    ],
  },
  {
    id: 'template-5',
    name: 'Minimal Dark',
    category: 'Minimal',
    thumbnail: '/templates/minimal-dark.jpg',
    canvas: { width: 1280, height: 720, backgroundColor: '#000000' },
    elements: [
      {
        id: 'bg',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 1280, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        locked: false,
        visible: true,
        fill: '#000000',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'title',
        type: 'text',
        text: 'THE TRUTH',
        position: { x: 80, y: 300 },
        size: { width: 700, height: 80 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 72,
          color: '#ffffff',
          textAlign: 'left',
          letterSpacing: 8,
        },
      } as TextElement,
      {
        id: 'line',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 80, y: 400 },
        size: { width: 100, height: 4 },
        rotation: 0,
        opacity: 1,
        zIndex: 1,
        locked: false,
        visible: true,
        fill: '#f59e0b',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
    ],
  },
  {
    id: 'template-6',
    name: 'Gradient Pop',
    category: 'Music',
    thumbnail: '/templates/gradient-pop.jpg',
    canvas: { width: 1280, height: 720, backgroundColor: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
    elements: [
      {
        id: 'bg',
        type: 'shape',
        shapeType: 'rectangle',
        position: { x: 0, y: 0 },
        size: { width: 1280, height: 720 },
        rotation: 0,
        opacity: 1,
        zIndex: 0,
        locked: false,
        visible: true,
        fill: '#667eea',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'circle1',
        type: 'shape',
        shapeType: 'circle',
        position: { x: -100, y: -100 },
        size: { width: 400, height: 400 },
        rotation: 0,
        opacity: 0.5,
        zIndex: 1,
        locked: false,
        visible: true,
        fill: '#764ba2',
        stroke: 'none',
        strokeWidth: 0,
      } as ShapeElement,
      {
        id: 'title',
        type: 'text',
        text: 'NEW MUSIC\nDROP',
        position: { x: 100, y: 240 },
        size: { width: 600, height: 200 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 64,
          color: '#ffffff',
          textAlign: 'left',
          lineHeight: 1.1,
          textShadow: '0px 4px 12px rgba(0,0,0,0.3)',
        },
      } as TextElement,
      {
        id: 'artist',
        type: 'text',
        text: 'Artist Name',
        position: { x: 100, y: 470 },
        size: { width: 400, height: 50 },
        rotation: 0,
        opacity: 1,
        zIndex: 2,
        locked: false,
        visible: true,
        style: {
          ...defaultTextStyle,
          fontSize: 24,
          color: '#e9d5ff',
          textAlign: 'left',
        },
      } as TextElement,
    ],
  },
];

export const CATEGORIES = [
  'All',
  'Gaming',
  'Tech',
  'Vlog',
  'Education',
  'Music',
  'Minimal',
  'Business',
  'Lifestyle',
];

export const POPULAR_FONTS = [
  'Arial',
  'Impact',
  'Montserrat',
  'Poppins',
  'Bebas Neue',
  'Oswald',
  'Roboto',
  'Open Sans',
  'Lato',
  'Inter',
  'Playfair Display',
  'Merriweather',
];

export const PRESET_COLORS = [
  '#ffffff', '#000000', '#dc2626', '#ea580c', '#d97706',
  '#ca8a04', '#65a30d', '#16a34a', '#059669', '#0d9488',
  '#0891b2', '#0284c7', '#2563eb', '#4f46e5', '#7c3aed',
  '#9333ea', '#c026d3', '#db2777', '#e11d48', '#f43f5e',
];
